package main

// `captain task mcp` - a stdio MCP server exposing the versioned task API
// (ROADMAP M4.2). Where the Euclid MCP server exposes memory tools, this
// server exposes the seven execution operations — plan, submit, inspect,
// events, artifacts, cancel, resume — so a host like Pi, Jido or an editor
// can delegate coding work to Captain through MCP rather than HTTP.
//
// Transport: newline-delimited JSON-RPC 2.0 on stdin/stdout (MCP stdio),
// the same transport as the Euclid MCP server. Each tool call constructs a
// TaskRequest envelope, posts it to the brain's /v1/task endpoint, and
// returns the response body as text content. The brain is the authority;
// the MCP server is a thin adapter that speaks MCP on one side and the
// versioned task API on the other.
//
// One internal lifecycle for HTTP and MCP: the same TaskRequest/TaskResponse
// envelope, the same error taxonomy, the same delegation lineage validation.
// A host that switches from HTTP to MCP does not get a different contract.

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"sync"
	"time"

	"github.com/lemma-ventures/captaincode/pkg/captaincode"
)

// mcpTasksProtocolVersion is the protocol version that introduced the
// experimental Tasks capability. A client that requests this version gets
// task-level semantics; a client on an older version gets tools only.
const mcpTasksProtocolVersion = "2025-11-25"

// mcpTaskDefaultTTL is the default task lifetime in milliseconds (1 hour).
const mcpTaskDefaultTTL = 3600000

// mcpTaskPollInterval is the suggested polling interval in milliseconds.
const mcpTaskPollInterval = 5000

// mcpTaskResultTimeout is how long tasks/result blocks before returning
// an error suggesting the client poll with tasks/get instead.
const mcpTaskResultTimeout = 120 * time.Second

// mcpTask maps an MCP task to its Captain task. The MCP task ID is
// generated by this server (the receiver); the Captain task ID comes from
// the brain's submit response. The MCP task tracks the Captain task's
// lifecycle and translates it to the MCP task status vocabulary.
type mcpTask struct {
	ID          string
	CaptainID   string
	ToolName    string
	Status      string // working, input_required, completed, failed, cancelled
	StatusMsg   string
	CreatedAt   time.Time
	LastUpdated time.Time
	TTL         int64          // milliseconds
	Result      map[string]any // stored tool result when terminal
	ResultErr   *rpcError
}

// taskMCPSession is the per-connection state: the negotiated protocol
// version, whether the client declared tasks capability, and the task
// store. The task store is process-local — the brain has the durable
// state; this is the mapping layer that gives an MCP client task-level
// semantics over the HTTP task API.
type taskMCPSession struct {
	mu             sync.Mutex
	tasks          map[string]*mcpTask
	order          []string // task IDs in creation order, for tasks/list
	version        string   // negotiated protocol version
	clientHasTasks bool     // client declared tasks capability
}

func newTaskMCPSession() *taskMCPSession {
	return &taskMCPSession{tasks: make(map[string]*mcpTask)}
}

// lifecycleToMCPStatus maps Captain lifecycle states to MCP task statuses.
// The MCP spec defines five statuses: working, input_required, completed,
// failed, cancelled. Captain has nine states; the mapping is many-to-one.
func lifecycleToMCPStatus(s captaincode.LifecycleState) string {
	switch s {
	case captaincode.StateAdmitted, captaincode.StateRunning:
		return "working"
	case captaincode.StateWaitingForInput:
		return "input_required"
	case captaincode.StateSucceeded:
		return "completed"
	case captaincode.StateCancelled:
		return "cancelled"
	case captaincode.StateFailed, captaincode.StateExhausted, captaincode.StateInterrupted:
		return "failed"
	}
	return "working"
}

func (s *taskMCPSession) putTask(t *mcpTask) {
	s.mu.Lock()
	s.tasks[t.ID] = t
	s.order = append(s.order, t.ID)
	s.mu.Unlock()
}

func (s *taskMCPSession) getTask(id string) (*mcpTask, bool) {
	s.mu.Lock()
	t, ok := s.tasks[id]
	s.mu.Unlock()
	return t, ok
}

func (s *taskMCPSession) updateTask(id string, status, msg string) {
	s.mu.Lock()
	if t, ok := s.tasks[id]; ok {
		t.Status = status
		t.StatusMsg = msg
		t.LastUpdated = time.Now()
	}
	s.mu.Unlock()
}

func (s *taskMCPSession) allTasks() []*mcpTask {
	s.mu.Lock()
	out := make([]*mcpTask, 0, len(s.order))
	for _, id := range s.order {
		if t, ok := s.tasks[id]; ok {
			out = append(out, t)
		}
	}
	s.mu.Unlock()
	return out
}

// mcpTaskResult is the MCP Task object returned in responses.
type mcpTaskResult struct {
	TaskID        string `json:"taskId"`
	Status        string `json:"status"`
	StatusMessage string `json:"statusMessage,omitempty"`
	CreatedAt     string `json:"createdAt"`
	LastUpdatedAt string `json:"lastUpdatedAt"`
	TTL           *int64 `json:"ttl"`
	PollInterval  int64  `json:"pollInterval,omitempty"`
}

func toMCPTaskResult(t *mcpTask) mcpTaskResult {
	ttl := t.TTL
	return mcpTaskResult{
		TaskID:        t.ID,
		Status:        t.Status,
		StatusMessage: t.StatusMsg,
		CreatedAt:     t.CreatedAt.UTC().Format(time.RFC3339),
		LastUpdatedAt: t.LastUpdated.UTC().Format(time.RFC3339),
		TTL:           &ttl,
		PollInterval:  mcpTaskPollInterval,
	}
}

var taskMCPTools = []map[string]any{
	{"name": "task_plan", "description": "Assess a task and return a routing plan (selected leg, class, rationale, decision) without executing it. Plan may consume a bounded planning allowance but cannot run a worker.",
		"inputSchema": map[string]any{"type": "object", "properties": map[string]any{
			"prompt":       map[string]any{"type": "string", "description": "the task prompt"},
			"prefer":       map[string]any{"type": "string", "description": "quality | speed | save | frontier"},
			"project_root": map[string]any{"type": "string", "description": "project root directory (optional)"},
		}, "required": []string{"prompt"}}},
	{"name": "task_submit", "description": "Submit a task for execution. Returns a durable task ID. A duplicate identical request attaches to the existing task; reuse with different scope/policy/input is a conflict. Supports task augmentation: include a \"task\" field in the call params to receive a CreateTaskResult and poll via tasks/get.",
		"inputSchema": map[string]any{"type": "object", "properties": map[string]any{
			"prompt":       map[string]any{"type": "string", "description": "the task prompt"},
			"leg":          map[string]any{"type": "string", "description": "force a specific leg (optional)"},
			"task_id":      map[string]any{"type": "string", "description": "reuse an existing task ID (optional)"},
			"project_root": map[string]any{"type": "string", "description": "project root directory (optional)"},
		}, "required": []string{"prompt"}},
		"execution": map[string]any{"taskSupport": "optional"}},
	{"name": "task_inspect", "description": "Read a task's full state: lifecycle, attempts, charges, budget, decision, and handoff brief if one exists.",
		"inputSchema": map[string]any{"type": "object", "properties": map[string]any{
			"task_id":          map[string]any{"type": "string", "description": "the task to inspect"},
			"include_charges":  map[string]any{"type": "boolean", "description": "include charge records (default true)"},
			"include_budget":   map[string]any{"type": "boolean", "description": "include budget (default true)"},
			"include_decision": map[string]any{"type": "boolean", "description": "include decision record (default true)"},
			"include_handoff":  map[string]any{"type": "boolean", "description": "include handoff brief (default true)"},
		}, "required": []string{"task_id"}}},
	{"name": "task_events", "description": "Read a bounded batch of task events from a cursor. Disconnect resumes observation, not execution. Pass the next_cursor from the previous batch to continue.",
		"inputSchema": map[string]any{"type": "object", "properties": map[string]any{
			"task_id": map[string]any{"type": "string", "description": "the task to read events for"},
			"cursor":  map[string]any{"type": "string", "description": "opaque cursor from a previous batch (optional)"},
			"limit":   map[string]any{"type": "integer", "description": "max events per batch (default 50, max 100)"},
		}, "required": []string{"task_id"}}},
	{"name": "task_artifacts", "description": "Read patch manifests and integration candidates for a task. Returns digests and changed-file lists, not file contents.",
		"inputSchema": map[string]any{"type": "object", "properties": map[string]any{
			"task_id":       map[string]any{"type": "string", "description": "the task to read artifacts for"},
			"include_diffs": map[string]any{"type": "boolean", "description": "include diff content (optional)"},
		}, "required": []string{"task_id"}}},
	{"name": "task_cancel", "description": "Cancel a task and all its descendants. Fires the cancellation tree for model calls, subprocesses, gates, review and nested work.",
		"inputSchema": map[string]any{"type": "object", "properties": map[string]any{
			"task_id": map[string]any{"type": "string", "description": "the task to cancel"},
			"reason":  map[string]any{"type": "string", "description": "cancellation reason (optional)"},
		}, "required": []string{"task_id"}}},
	{"name": "task_resume", "description": "Create a new attempt under an interrupted task. The new attempt shares the task's remaining budget and has a causal link to the interrupted attempt.",
		"inputSchema": map[string]any{"type": "object", "properties": map[string]any{
			"task_id":    map[string]any{"type": "string", "description": "the task to resume"},
			"attempt_id": map[string]any{"type": "string", "description": "the interrupted attempt to resume from"},
			"reason":     map[string]any{"type": "string", "description": "resume reason (optional)"},
		}, "required": []string{"task_id", "attempt_id"}}},
}

func strArg(args map[string]any, k string) string {
	v, _ := args[k].(string)
	return strings.TrimSpace(v)
}

func intArg(args map[string]any, k string, def int) int {
	if v, ok := args[k].(float64); ok && v > 0 {
		return int(v)
	}
	return def
}

func boolArg(args map[string]any, k string, def bool) bool {
	if v, ok := args[k].(bool); ok {
		return v
	}
	return def
}

func taskMCPToolCall(name string, args map[string]any) (map[string]any, error) {
	text := func(s string) map[string]any {
		return map[string]any{"content": []map[string]any{{"type": "text", "text": s}}}
	}

	switch name {
	case "task_plan":
		prompt := strArg(args, "prompt")
		if prompt == "" {
			return nil, fmt.Errorf("prompt is required")
		}
		intent := captaincode.TaskIntent{Prefer: strArg(args, "prefer")}
		if strArg(args, "prefer") == "frontier" {
			intent.Frontier = true
		}
		body := captaincode.PlanRequest{Prompt: prompt, Intent: intent}
		bodyJSON, _ := json.Marshal(body)
		resp := postTaskAPI(captaincode.OpPlan, "", bodyJSON)
		return text(formatPlanResponse(resp)), nil

	case "task_submit":
		prompt := strArg(args, "prompt")
		if prompt == "" {
			return nil, fmt.Errorf("prompt is required")
		}
		body := captaincode.SubmitRequest{Prompt: prompt}
		if leg := strArg(args, "leg"); leg != "" {
			body.Leg = captaincode.Leg(leg)
		}
		bodyJSON, _ := json.Marshal(body)
		taskID := strArg(args, "task_id")
		resp := postTaskAPI(captaincode.OpSubmit, taskID, bodyJSON)
		return text(formatSubmitResponse(resp)), nil

	case "task_inspect":
		taskID := strArg(args, "task_id")
		if taskID == "" {
			return nil, fmt.Errorf("task_id is required")
		}
		body := captaincode.InspectRequest{
			IncludeCharges:  boolArg(args, "include_charges", true),
			IncludeBudget:   boolArg(args, "include_budget", true),
			IncludeDecision: boolArg(args, "include_decision", true),
			IncludeHandoff:  boolArg(args, "include_handoff", true),
		}
		bodyJSON, _ := json.Marshal(body)
		resp := postTaskAPI(captaincode.OpInspect, taskID, bodyJSON)
		return text(formatInspectResponse(resp)), nil

	case "task_events":
		taskID := strArg(args, "task_id")
		if taskID == "" {
			return nil, fmt.Errorf("task_id is required")
		}
		body := captaincode.EventsRequest{
			Cursor: strArg(args, "cursor"),
			Limit:  intArg(args, "limit", 50),
		}
		bodyJSON, _ := json.Marshal(body)
		resp := postTaskAPI(captaincode.OpEvents, taskID, bodyJSON)
		return text(formatEventsResponse(resp)), nil

	case "task_artifacts":
		taskID := strArg(args, "task_id")
		if taskID == "" {
			return nil, fmt.Errorf("task_id is required")
		}
		body := captaincode.ArtifactsRequest{IncludeDiffs: boolArg(args, "include_diffs", false)}
		bodyJSON, _ := json.Marshal(body)
		resp := postTaskAPI(captaincode.OpArtifacts, taskID, bodyJSON)
		return text(formatArtifactsResponse(resp)), nil

	case "task_cancel":
		taskID := strArg(args, "task_id")
		if taskID == "" {
			return nil, fmt.Errorf("task_id is required")
		}
		body := captaincode.CancelRequest{Reason: strArg(args, "reason")}
		bodyJSON, _ := json.Marshal(body)
		resp := postTaskAPI(captaincode.OpCancel, taskID, bodyJSON)
		return text(formatCancelResponse(resp)), nil

	case "task_resume":
		taskID := strArg(args, "task_id")
		if taskID == "" {
			return nil, fmt.Errorf("task_id is required")
		}
		attemptID := strArg(args, "attempt_id")
		if attemptID == "" {
			return nil, fmt.Errorf("attempt_id is required")
		}
		body := captaincode.ResumeRequest{AttemptID: attemptID, Reason: strArg(args, "reason")}
		bodyJSON, _ := json.Marshal(body)
		resp := postTaskAPI(captaincode.OpResume, taskID, bodyJSON)
		return text(formatResumeResponse(resp)), nil
	}

	return nil, fmt.Errorf("unknown tool %q", name)
}

func postTaskAPI(op captaincode.Operation, taskID string, bodyJSON []byte) *captaincode.TaskResponse {
	req := captaincode.TaskRequest{
		Version:   captaincode.TaskAPIVersion,
		Op:        op,
		RequestID: captaincode.NewRequestID(),
		TaskID:    taskID,
		Body:      bodyJSON,
	}
	reqJSON, _ := json.Marshal(req)
	c := &http.Client{Timeout: 120 * time.Second}
	resp, err := c.Post(brainURL()+"/v1/task", "application/json", bytes.NewReader(reqJSON))
	if err != nil {
		return &captaincode.TaskResponse{
			Version: captaincode.TaskAPIVersion,
			Status:  captaincode.ResponseError,
			Error:   captaincode.NewTaskError(captaincode.ErrUnavailable, "brain not reachable: "+err.Error()),
		}
	}
	defer resp.Body.Close()
	var tresp captaincode.TaskResponse
	json.NewDecoder(resp.Body).Decode(&tresp)
	return &tresp
}

func formatTaskError(resp *captaincode.TaskResponse) string {
	if resp == nil || resp.Status != captaincode.ResponseError || resp.Error == nil {
		return ""
	}
	return fmt.Sprintf("error: %s: %s", resp.Error.Code, resp.Error.Message)
}

func formatPlanResponse(resp *captaincode.TaskResponse) string {
	if e := formatTaskError(resp); e != "" {
		return e
	}
	var plan captaincode.PlanResponse
	json.Unmarshal(resp.Body, &plan)
	var sb strings.Builder
	fmt.Fprintf(&sb, "leg: %s\n", plan.Leg)
	fmt.Fprintf(&sb, "class: %s\n", plan.Class)
	if plan.Domain != "" {
		fmt.Fprintf(&sb, "domain: %s\n", plan.Domain)
	}
	fmt.Fprintf(&sb, "rationale: %s\n", plan.Rationale)
	if plan.EstDurationSupported {
		fmt.Fprintf(&sb, "est_duration: %dms\n", plan.EstDurationMs)
	}
	if plan.EstCostUSD > 0 {
		fmt.Fprintf(&sb, "est_cost: $%.4f\n", plan.EstCostUSD)
	}
	return strings.TrimSpace(sb.String())
}

func formatSubmitResponse(resp *captaincode.TaskResponse) string {
	if e := formatTaskError(resp); e != "" {
		return e
	}
	var sub captaincode.SubmitResponse
	json.Unmarshal(resp.Body, &sub)
	var sb strings.Builder
	fmt.Fprintf(&sb, "task_id: %s\n", sub.TaskID)
	fmt.Fprintf(&sb, "state: %s\n", sub.State)
	if sub.Attempt != "" {
		fmt.Fprintf(&sb, "attempt: %s\n", sub.Attempt)
	}
	return strings.TrimSpace(sb.String())
}

func formatInspectResponse(resp *captaincode.TaskResponse) string {
	if e := formatTaskError(resp); e != "" {
		return e
	}
	var insp captaincode.InspectResponse
	json.Unmarshal(resp.Body, &insp)
	var sb strings.Builder
	if insp.Task != nil {
		fmt.Fprintf(&sb, "task: %s — %s\n", insp.Task.TaskID, insp.Task.State)
		if insp.Task.StopReason != "" {
			fmt.Fprintf(&sb, "  stop: %s\n", insp.Task.StopReason)
		}
	}
	for _, a := range insp.Attempts {
		fmt.Fprintf(&sb, "  attempt %s — %s (leg: %s)\n", a.AttemptID, a.State, a.Leg)
	}
	if insp.Budget != nil {
		fmt.Fprintf(&sb, "  budget: %d/%d attempts", insp.Budget.SettledAttempts, insp.Budget.MaxAttempts)
		if insp.Budget.SettledCostUSD > 0 {
			fmt.Fprintf(&sb, ", $%.4f", insp.Budget.SettledCostUSD)
		}
		fmt.Fprintln(&sb)
	}
	if insp.Decision != nil {
		fmt.Fprintf(&sb, "  decision: %s (path: %s)\n", insp.Decision.Chosen, insp.Decision.Path)
	}
	if insp.Handoff != nil {
		sb.WriteString("\n" + captaincode.FormatHandoffBrief(*insp.Handoff))
	}
	return strings.TrimSpace(sb.String())
}

func formatEventsResponse(resp *captaincode.TaskResponse) string {
	if e := formatTaskError(resp); e != "" {
		return e
	}
	var evs captaincode.EventsResponse
	json.Unmarshal(resp.Body, &evs)
	if len(evs.Events) == 0 {
		return "no events."
	}
	var sb strings.Builder
	for _, e := range evs.Events {
		fmt.Fprintf(&sb, "  %s [%s] %s", e.At.Format("15:04:05"), e.Kind, e.Leg)
		if e.Detail != "" {
			fmt.Fprintf(&sb, " — %s", truncate(e.Detail, 60))
		}
		fmt.Fprintln(&sb)
	}
	if evs.HasMore {
		fmt.Fprintf(&sb, "\nmore events available (cursor: %s)\n", evs.NextCursor)
	}
	return strings.TrimSpace(sb.String())
}

func formatArtifactsResponse(resp *captaincode.TaskResponse) string {
	if e := formatTaskError(resp); e != "" {
		return e
	}
	var arts captaincode.ArtifactsResponse
	json.Unmarshal(resp.Body, &arts)
	if arts.Integration == nil {
		return "no artifacts for task."
	}
	var sb strings.Builder
	fmt.Fprintf(&sb, "integration: %s\n", arts.Integration.Status)
	for _, m := range arts.Manifests {
		fmt.Fprintf(&sb, "  · %s — %d file(s)", m.Leg, len(m.ChangedFiles))
		if m.Check != nil {
			if m.Check.Passed {
				sb.WriteString(" [check passed]")
			} else {
				sb.WriteString(" [check failed]")
			}
		}
		fmt.Fprintln(&sb)
	}
	if len(arts.Integration.Conflicts) > 0 {
		sb.WriteString("conflicts:\n")
		for _, c := range arts.Integration.Conflicts {
			fmt.Fprintf(&sb, "  · %s (%s)\n", c.File, strings.Join(c.Workers, ", "))
		}
	}
	return strings.TrimSpace(sb.String())
}

func formatCancelResponse(resp *captaincode.TaskResponse) string {
	if e := formatTaskError(resp); e != "" {
		return e
	}
	var can captaincode.CancelResponse
	json.Unmarshal(resp.Body, &can)
	var sb strings.Builder
	fmt.Fprintf(&sb, "task %s — %s\n", can.TaskID, can.State)
	if len(can.Cancelled) > 0 {
		fmt.Fprintf(&sb, "cancelled %d item(s):\n", len(can.Cancelled))
		for _, label := range can.Cancelled {
			fmt.Fprintf(&sb, "  · %s\n", label)
		}
	} else {
		sb.WriteString("no in-flight work.\n")
	}
	return strings.TrimSpace(sb.String())
}

func formatResumeResponse(resp *captaincode.TaskResponse) string {
	if e := formatTaskError(resp); e != "" {
		return e
	}
	var res captaincode.ResumeResponse
	json.Unmarshal(resp.Body, &res)
	var sb strings.Builder
	fmt.Fprintf(&sb, "task %s — %s\n", res.TaskID, res.State)
	fmt.Fprintf(&sb, "attempt: %s\n", res.AttemptID)
	if res.ParentAttempt != "" {
		fmt.Fprintf(&sb, "resumed from: %s\n", res.ParentAttempt)
	}
	if res.Budget != nil {
		fmt.Fprintf(&sb, "budget: %d/%d attempts\n", res.Budget.SettledAttempts, res.Budget.MaxAttempts)
	}
	return strings.TrimSpace(sb.String())
}

func serveTaskMCP(in io.Reader, out io.Writer) {
	serveTaskMCPWithSession(in, out, newTaskMCPSession())
}

func serveTaskMCPWithSession(in io.Reader, out io.Writer, sess *taskMCPSession) {
	sc := bufio.NewScanner(in)
	sc.Buffer(make([]byte, 0, 64*1024), 4*1024*1024)
	enc := json.NewEncoder(out)
	var encMu sync.Mutex
	reply := func(id json.RawMessage, result any, err *rpcError) {
		if len(id) == 0 {
			return
		}
		encMu.Lock()
		_ = enc.Encode(rpcResponse{JSONRPC: "2.0", ID: id, Result: result, Error: err})
		encMu.Unlock()
	}
	notify := func(method string, params any) {
		encMu.Lock()
		_ = enc.Encode(rpcResponse{JSONRPC: "2.0", Result: params})
		encMu.Unlock()
	}
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" {
			continue
		}
		var req rpcRequest
		if json.Unmarshal([]byte(line), &req) != nil {
			continue
		}
		switch req.Method {
		case "initialize":
			var p struct {
				ProtocolVersion string         `json:"protocolVersion"`
				Capabilities    map[string]any `json:"capabilities"`
				ClientInfo      map[string]any `json:"clientInfo"`
			}
			_ = json.Unmarshal(req.Params, &p)
			sess.version = negotiateMCPVersion(p.ProtocolVersion)
			sess.clientHasTasks = clientDeclaresTasks(p.Capabilities)
			caps := map[string]any{"tools": map[string]any{}}
			if sess.version == mcpTasksProtocolVersion {
				caps["tasks"] = map[string]any{
					"list":   map[string]any{},
					"cancel": map[string]any{},
					"requests": map[string]any{
						"tools": map[string]any{"call": map[string]any{}},
					},
				}
			}
			reply(req.ID, map[string]any{
				"protocolVersion": sess.version,
				"capabilities":    caps,
				"serverInfo":      map[string]any{"name": "captain-task", "version": "0.1.0"},
			}, nil)
		case "notifications/initialized", "notifications/cancelled":
		case "ping":
			reply(req.ID, map[string]any{}, nil)
		case "tools/list":
			reply(req.ID, map[string]any{"tools": taskMCPTools}, nil)
		case "tools/call":
			var p struct {
				Name      string         `json:"name"`
				Arguments map[string]any `json:"arguments"`
				Task      *struct {
					TTL int64 `json:"ttl,omitempty"`
				} `json:"task,omitempty"`
			}
			_ = json.Unmarshal(req.Params, &p)
			if p.Task != nil && sess.version == mcpTasksProtocolVersion {
				handleTaskAugmentedCall(req.ID, p.Name, p.Arguments, p.Task.TTL, sess, reply, notify)
				continue
			}
			res, err := taskMCPToolCall(p.Name, p.Arguments)
			if err != nil {
				reply(req.ID, map[string]any{"content": []map[string]any{{"type": "text", "text": err.Error()}}, "isError": true}, nil)
				continue
			}
			reply(req.ID, res, nil)
		case "tasks/get":
			handleTasksGet(req, sess, reply, notify)
		case "tasks/result":
			handleTasksResult(req, sess, reply)
		case "tasks/list":
			handleTasksList(req, sess, reply)
		case "tasks/cancel":
			handleTasksCancel(req, sess, reply)
		default:
			reply(req.ID, nil, &rpcError{Code: -32601, Message: "method not found: " + req.Method})
		}
	}
}

// negotiateMCPVersion picks the protocol version both sides can speak.
// If the client requests 2025-11-25, the server responds with it (Tasks
// enabled). Otherwise the server falls back to 2025-06-18 (tools only).
func negotiateMCPVersion(client string) string {
	if client == mcpTasksProtocolVersion {
		return mcpTasksProtocolVersion
	}
	return mcpProtocolVersion
}

// clientDeclaresTasks checks whether the client's initialize capabilities
// include the tasks capability. The server only uses Tasks methods when
// both sides declared it.
func clientDeclaresTasks(caps map[string]any) bool {
	if caps == nil {
		return false
	}
	tasks, ok := caps["tasks"].(map[string]any)
	return ok && len(tasks) > 0
}

// mcpReplyFunc is the reply closure signature shared by all handlers.
type mcpReplyFunc func(id json.RawMessage, result any, err *rpcError)

// mcpNotifyFunc is the notification closure signature.
type mcpNotifyFunc func(method string, params any)

// handleTaskAugmentedCall processes a tools/call request that includes a
// task field. The server submits the task to the brain, creates an MCP
// task entry, and returns a CreateTaskResult immediately — the actual
// tool result is retrieved later via tasks/result.
func handleTaskAugmentedCall(id json.RawMessage, name string, args map[string]any, ttl int64, sess *taskMCPSession, reply mcpReplyFunc, notify mcpNotifyFunc) {
	if name != "task_submit" && name != "task_resume" {
		reply(id, nil, &rpcError{Code: -32600, Message: "tool " + name + " does not support task augmentation"})
		return
	}
	var captainID string
	switch name {
	case "task_submit":
		prompt := strArg(args, "prompt")
		if prompt == "" {
			reply(id, nil, &rpcError{Code: -32602, Message: "prompt is required"})
			return
		}
		body := captaincode.SubmitRequest{Prompt: prompt}
		if leg := strArg(args, "leg"); leg != "" {
			body.Leg = captaincode.Leg(leg)
		}
		resp := postTaskAPI(captaincode.OpSubmit, strArg(args, "task_id"), mustJSON(body))
		if resp.Status == captaincode.ResponseError {
			reply(id, nil, &rpcError{Code: -32603, Message: formatTaskError(resp)})
			return
		}
		var sub captaincode.SubmitResponse
		json.Unmarshal(resp.Body, &sub)
		captainID = sub.TaskID
	case "task_resume":
		taskID := strArg(args, "task_id")
		attemptID := strArg(args, "attempt_id")
		if taskID == "" || attemptID == "" {
			reply(id, nil, &rpcError{Code: -32602, Message: "task_id and attempt_id are required"})
			return
		}
		body := captaincode.ResumeRequest{AttemptID: attemptID}
		resp := postTaskAPI(captaincode.OpResume, taskID, mustJSON(body))
		if resp.Status == captaincode.ResponseError {
			reply(id, nil, &rpcError{Code: -32603, Message: formatTaskError(resp)})
			return
		}
		var rrm captaincode.ResumeResponse
		json.Unmarshal(resp.Body, &rrm)
		captainID = rrm.TaskID
	}
	if captainID == "" {
		reply(id, nil, &rpcError{Code: -32603, Message: "task creation failed: no task ID in response"})
		return
	}
	if ttl <= 0 {
		ttl = mcpTaskDefaultTTL
	}
	now := time.Now()
	t := &mcpTask{
		ID:          captaincode.NewRequestID(),
		CaptainID:   captainID,
		ToolName:    name,
		Status:      "working",
		CreatedAt:   now,
		LastUpdated: now,
		TTL:         ttl,
	}
	sess.putTask(t)
	reply(id, map[string]any{"task": toMCPTaskResult(t)}, nil)
}

// handleTasksGet polls a task's current status by asking the brain to
// inspect the Captain task. The client SHOULD respect pollInterval and
// continue polling until a terminal status.
func handleTasksGet(req rpcRequest, sess *taskMCPSession, reply mcpReplyFunc, notify mcpNotifyFunc) {
	var p struct {
		TaskID string `json:"taskId"`
	}
	_ = json.Unmarshal(req.Params, &p)
	if p.TaskID == "" {
		reply(req.ID, nil, &rpcError{Code: -32602, Message: "taskId is required"})
		return
	}
	t, ok := sess.getTask(p.TaskID)
	if !ok {
		reply(req.ID, nil, &rpcError{Code: -32602, Message: "task not found: " + p.TaskID})
		return
	}
	if isTerminalMCP(t.Status) {
		reply(req.ID, toMCPTaskResult(t), nil)
		return
	}
	inspectResp := postTaskAPI(captaincode.OpInspect, t.CaptainID, mustJSON(captaincode.InspectRequest{IncludeCharges: false, IncludeBudget: false, IncludeDecision: false, IncludeHandoff: false}))
	if inspectResp.Status == captaincode.ResponseError {
		reply(req.ID, toMCPTaskResult(t), nil)
		return
	}
	var insp captaincode.InspectResponse
	json.Unmarshal(inspectResp.Body, &insp)
	if insp.Task != nil {
		newStatus := lifecycleToMCPStatus(insp.Task.State)
		if newStatus != t.Status {
			sess.updateTask(t.ID, newStatus, "")
			t.Status = newStatus
			t.LastUpdated = time.Now()
			notify("notifications/tasks/status", toMCPTaskResult(t))
		}
	}
	reply(req.ID, toMCPTaskResult(t), nil)
}

// handleTasksResult returns the final tool result for a terminal task.
// For non-terminal tasks, it blocks (polling the brain) until the task
// reaches a terminal status or the timeout expires.
func handleTasksResult(req rpcRequest, sess *taskMCPSession, reply mcpReplyFunc) {
	var p struct {
		TaskID string `json:"taskId"`
	}
	_ = json.Unmarshal(req.Params, &p)
	if p.TaskID == "" {
		reply(req.ID, nil, &rpcError{Code: -32602, Message: "taskId is required"})
		return
	}
	t, ok := sess.getTask(p.TaskID)
	if !ok {
		reply(req.ID, nil, &rpcError{Code: -32602, Message: "task not found: " + p.TaskID})
		return
	}
	deadline := time.Now().Add(mcpTaskResultTimeout)
	for !isTerminalMCP(t.Status) && time.Now().Before(deadline) {
		time.Sleep(time.Duration(mcpTaskPollInterval) * time.Millisecond)
		inspectResp := postTaskAPI(captaincode.OpInspect, t.CaptainID, mustJSON(captaincode.InspectRequest{IncludeCharges: true, IncludeBudget: true, IncludeDecision: true, IncludeHandoff: true}))
		if inspectResp.Status == captaincode.ResponseError {
			break
		}
		var insp captaincode.InspectResponse
		json.Unmarshal(inspectResp.Body, &insp)
		if insp.Task != nil {
			newStatus := lifecycleToMCPStatus(insp.Task.State)
			if newStatus != t.Status {
				sess.updateTask(t.ID, newStatus, "")
				t.Status = newStatus
				t.LastUpdated = time.Now()
			}
		}
	}
	if !isTerminalMCP(t.Status) {
		reply(req.ID, nil, &rpcError{Code: -32603, Message: "task not yet terminal; poll with tasks/get"})
		return
	}
	inspectResp := postTaskAPI(captaincode.OpInspect, t.CaptainID, mustJSON(captaincode.InspectRequest{IncludeCharges: true, IncludeBudget: true, IncludeDecision: true, IncludeHandoff: true}))
	text := formatInspectResponse(inspectResp)
	if inspectResp.Status == captaincode.ResponseError {
		text = formatTaskError(inspectResp)
	}
	result := map[string]any{
		"content": []map[string]any{{"type": "text", "text": text}},
		"_meta":   map[string]any{"io.modelcontextprotocol/related-task": map[string]any{"taskId": t.ID}},
	}
	if t.Status == "failed" {
		result["isError"] = true
	}
	reply(req.ID, result, nil)
}

// handleTasksList returns all tracked tasks with cursor-based pagination.
func handleTasksList(req rpcRequest, sess *taskMCPSession, reply mcpReplyFunc) {
	var p struct {
		Cursor string `json:"cursor,omitempty"`
	}
	_ = json.Unmarshal(req.Params, &p)
	all := sess.allTasks()
	pageSize := 50
	start := 0
	if p.Cursor != "" {
		for i, t := range all {
			if t.ID == p.Cursor {
				start = i + 1
				break
			}
		}
	}
	end := start + pageSize
	if end > len(all) {
		end = len(all)
	}
	if start >= len(all) {
		reply(req.ID, map[string]any{"tasks": []any{}}, nil)
		return
	}
	tasks := make([]any, 0, end-start)
	for _, t := range all[start:end] {
		tasks = append(tasks, toMCPTaskResult(t))
	}
	resp := map[string]any{"tasks": tasks}
	if end < len(all) {
		resp["nextCursor"] = all[end-1].ID
	}
	reply(req.ID, resp, nil)
}

// handleTasksCancel cancels a task. Terminal tasks are rejected with
// -32602 (Invalid params) per the spec. Non-terminal tasks are cancelled
// via the brain's cancel endpoint.
func handleTasksCancel(req rpcRequest, sess *taskMCPSession, reply mcpReplyFunc) {
	var p struct {
		TaskID string `json:"taskId"`
	}
	_ = json.Unmarshal(req.Params, &p)
	if p.TaskID == "" {
		reply(req.ID, nil, &rpcError{Code: -32602, Message: "taskId is required"})
		return
	}
	t, ok := sess.getTask(p.TaskID)
	if !ok {
		reply(req.ID, nil, &rpcError{Code: -32602, Message: "task not found: " + p.TaskID})
		return
	}
	if isTerminalMCP(t.Status) {
		reply(req.ID, nil, &rpcError{Code: -32602, Message: "cannot cancel task: already in terminal status '" + t.Status + "'"})
		return
	}
	cancelResp := postTaskAPI(captaincode.OpCancel, t.CaptainID, mustJSON(captaincode.CancelRequest{}))
	if cancelResp.Status == captaincode.ResponseError {
		reply(req.ID, nil, &rpcError{Code: -32603, Message: formatTaskError(cancelResp)})
		return
	}
	sess.updateTask(t.ID, "cancelled", "The task was cancelled by request.")
	t.Status = "cancelled"
	t.StatusMsg = "The task was cancelled by request."
	reply(req.ID, toMCPTaskResult(t), nil)
}

func isTerminalMCP(status string) bool {
	return status == "completed" || status == "failed" || status == "cancelled"
}

func mustJSON(v any) []byte {
	b, _ := json.Marshal(v)
	return b
}

func cmdTaskMCP() {
	serveTaskMCP(os.Stdin, os.Stdout)
}
